### ISSUE TITLE
App crashing on iphone 5

### ISSUE THREAD

**Issue by EladKeyshawn** [kiwix/iOS#62]
Just updated the app to the last release and went to the bookstore and from there non-stop crashing when opening the app.
Running on iPhone 5 IOS 10.3.1

**Comment by automactic** [comment]
I am sorry, @EladKeyshawn, you have to reinstall. 
After updating to 1.8, some user reported app crashing, this is mostly likely due to some compatibility issue with old version. The app migrated from swift 2.3 to swift 3 in 1.8, which is a huge change, a lot of stuff was rewritten. I have no way of fixing them.

**Comment by EladKeyshawn** [comment]
Alright @automactic 👍

**Comment by automactic** [comment]
@EladKeyshawn  BTW, how do you think of the app so far?

**Comment by EladKeyshawn** [comment]
@automactic  I think it's really great actually 😄

**Comment by automactic** [comment]
@EladKeyshawn Thanks! Any suggestions would always be appreciated! 😀
